### PR TITLE
Docz external resolve fix

### PR DESCRIPTION
**Pull request by ejuo**
Fix for #783

### CODE REVIEW

**Comment by patricksevat** [comment]
I think it's a nicer solution. But when trying to run examples I run into some an error:
```
These relative modules were not found:

* ./components/ui in C:/rfs/docz/core/docz-theme-default/dist/index.esm.js
* ./config in C:/rfs/docz/core/docz-theme-default/dist/index.esm.js
* ./styles/global in C:/rfs/docz/core/docz-theme-default/dist/index.esm.js
* ./styles/modes in C:/rfs/docz/core/docz-theme-default/dist/index.esm.js
* ./utils/theme in C:/rfs/docz/core/docz-theme-default/dist/index.esm.js
```
When removing the `external` prop in `docz-theme-default/rollup.config.js` it builds and runs correctly.

**Comment by ejuo** [comment]
> I think it's a nicer solution. But when trying to run examples I run into some an error:
> 
> ```
> These relative modules were not found:
> 
> * ./components/ui in C:/rfs/docz/core/docz-theme-default/dist/index.esm.js
> * ./config in C:/rfs/docz/core/docz-theme-default/dist/index.esm.js
> * ./styles/global in C:/rfs/docz/core/docz-theme-default/dist/index.esm.js
> * ./styles/modes in C:/rfs/docz/core/docz-theme-default/dist/index.esm.js
> * ./utils/theme in C:/rfs/docz/core/docz-theme-default/dist/index.esm.js
> ```
> When removing the `external` prop in `docz-theme-default/rollup.config.js` it builds and runs correctly.

Fix it, thanks.

**Comment by pedronauck** [comment]
You need to upgrade your branch dude, your commit changes with a lot of changelog stuff.

**Comment by ejuo** [comment]
> You need to upgrade your branch dude, your commit changes with a lot of changelog stuff.

@pedronauck , is it normal that the dev branch has version 1.0.3, unlike master 1.0.4?

**Comment by pedronauck** [comment]
It's not normal, thanks to the warning, it's both updated now 🙏

**Comment by ejuo** [comment]
@pedronauck , what else is required?

**Comment by pedronauck** [comment]
You need to update your branch, as you can see, as sow many files changed inside your pull request. Try to keep just the change that you made.

**Comment by ejuo** [comment]
@pedronauck, I I recreated the [PR](https://github.com/pedronauck/docz/pull/830), so that only current changes are visible.

**Pull request closed without merging**
