### PR TITLE
fix(docz-theme-default): ensures the overlay is hidden when the sidebar is collapsed

### PR DESCRIPTION
**Pull request by alec-francis**
### Description

Closes issue #850. This bug was also seen in earlier issues (#476, #293). 

Perhaps if we merge this pull request then we can have the confidence that the overlay will always be removed when the sidebar is hidden.

### CODE REVIEW

**Comment by pepibumur** [comment]
Is there any plan to merge this one?

**Comment by lemon-31** [comment]
@pepibumur I hope so too.

@pedronauck, what are your thoughts about this one?

**Comment by pedronauck** [comment]
This is no longer necessary since the [new v2](https://github.com/pedronauck/docz/pull/950).

**Comment by madou** [comment]
sweet, thanks @pedronauck 

will anything be done about scroll to top on navigation atm? any recommendations for fixing this in user land if we're waiting for v2?

**Comment by pedronauck** [comment]
I'll release v2 in the next few days, I think is best to wait until there. It's very close :v:

**Pull request closed without merging**
