### PR TITLE
fix(docz-theme-default): fix padding in Playground elements

### PR DESCRIPTION
**Pull request by kachkaev**
Resolves https://github.com/pedronauck/docz/issues/398#issuecomment-453663552

### Screenshots

**Before**

screenshot 2019-01-11 at 21 58 31

**After**

screenshot 2019-01-11 at 21 58 17

### CODE REVIEW

**Comment by pedronauck** [comment]
Thanks to the pull request, it's already merged into branch `v0.14` since the conflicts using cherry-pick.

**Comment by kachkaev** [comment]
Thanks! Looking forward for the release!

**Comment by kachkaev** [comment]
Hi @pedronauck! 👋 What are your thoughts on cutting a new release?

**Comment by pedronauck** [comment]
I'm preparing v1.0, I'll be launching in the couple weeks 🙏

**Pull request closed without merging**
