### PR TITLE
Fix/issue#528 Serve correct public folder

### PR DESCRIPTION
**Pull request by patricksevat**
### Description

Using `{ public: './public' }` in `doczrc.js` led to Express serving the wrong static path (at least on windows). This PR fixes that.

Tested on Windows 10 and on Ubuntu (on Windows Linux Subsystem) to test both win and posix file separators.

Tested with both relative paths and absolute paths on both OS.

### CODE REVIEW

**Comment by patricksevat** [comment]
I branched from master, let me know if I should rebase on dev

**Comment by sw-yx** [comment]
where do we publish from? master or dev? i didnt realize there was a difference and now i'm really not sure

**Comment by patricksevat** [comment]
Hi @pedronauck ,

Could you elaborate why you closed this PR? 
As far as I can test, this issue is still appears.

If you'd like I can reapply the fix to a new branch.

**Comment by idmontie** [comment]
@pedronauck  @patricksevat Just commenting to mention that the wrong folder is served for static assets on my Mac and changing the line to `app.use('/public', express.static(publicDirPath))` fixes the issue.

**Comment by pedronauck** [comment]
Sorry @patricksevat, I closed because your pull request was with a lot of diffs and this fix it's already done in the updated branch, I'm pretty hard working in a `v1` and it will be launched soon. So, this is kinda outdated.

**Comment by patricksevat** [comment]
@pedronauck thx for the reply. Glad to hear you fixed the issue and I'm looking forward to v1!

**Pull request closed without merging**
