### PR TITLE
HOWTO run demos locally (compile first!)

### PR DESCRIPTION
**Pull request by 100ideas**
### Description

added 'clone repo and run examples' section to README.md explicitly showing how to clone repo, compile packages, and run demos.

### CODE REVIEW

**Comment by pedronauck** [comment]
We already have this on our [Contributing](https://github.com/pedronauck/docz/blob/master/CONTRIBUTING.md) @100ideas :v:

**Comment by 100ideas** [comment]
I had read that page but it wasn't clear to me that "as a user who wants to try the demo" I needed to first build all the packages. 

Other monorepos I've worked with often seem to use "build" scripts for tasks related to production deployment and distributing packages. Local demos, dev documentation, and local dev often have separate script names and toolchains (even if in some cases they use the same build tooling).

I understand if you think the pr was providing redundant info. At the same time, my experience with the existing documentation led to confusion.

Maybe we could host the demos at codesandbox and keep them synced to the repo automatically so it's easier for prospective users to try things out.

**Comment by 100ideas** [comment]
Better idea: git-hook + netlify to `docz build` & host each of the examples.

**Comment by 100ideas** [comment]
here, got a basic thing working in codesandbox. it should stay up-to-date with this repo. https://codesandbox.io/s/y2y2ymxm19

**Pull request closed without merging**
