### PR TITLE
fix(gatsby-theme-docz): make Props isToggle work again

### LINKED ISSUE #1323: need a prop to set default visibility of props descriptions version 2+
## Question

seems a props form Props component is needed to control default visibility of props‘s descriptions

image

seems that `isToggle` means to do it but actually not

```tsx
<Props isToggle of={ComponentXX} />
```

https://github.com/doczjs/docz/blob/320f5c4ad8be1835cbc8498cee1dcb41afee0c85/core/docz/src/components/Props.tsx#L161

### PR DESCRIPTION
**Pull request by gogoyqj**
### Description

fix https://github.com/doczjs/docz/issues/1323

### Screenshots

| Before | After |
| ------ | ----- |
| image | image|

### CODE REVIEW

**Review by Dangoo — APPROVED** [review]
Checklist by @rakannimer:
- [x] Add isToggle argument in Props definition : https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/components/Props/index.js#L68
- [x] Pass isToggle down to Prop https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/components/Props/index.js#L74
- [x] Add isToggle argument in Prop definition : https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/components/Props/index.js#L23
- [x] Initialize showing state to isToggle https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/components/Props/index.js#L24

Syntactically looking good so far, thanks for your contribution!

**Review by rakannimer — APPROVED** [review]
Looks good 👍

**Comment by rakannimer** [comment]
Thanks @gogoyqj ! Will release an alpha and update here.

**Comment by rakannimer** [comment]
Will be released as 2.3.0. Currently released as 2.3.0-alpha.4. You can try it with : `yarn add docz@next`

**Comment by gogoyqj** [comment]
with pleasure

**Pull request merged**
