### PR TITLE
feat: use NODE_PATH for root directory(fix #396)

### LINKED ISSUE #396: Create react app with absolute imports (`NODE_PATH`)
### Description

Reading #140 I get the impression that [`NODE_PATH`](https://github.com/pedronauck/docz/pull/140/files#diff-9d590c3343581f61a481376bf7431eabR32) in `.env` should be supported.

I've gotten a create-react-app until the point of supporting absolute paths. Is there any way to tell docz to use `src` as `NODE_PATH`?

### Steps to reproduce

I've created an example in https://github.com/KATT/create-react-app-docz-test

```
git clone git@github.com:KATT/create-react-app-docz-test.git
cd create-react-app-docz-test
yarn docz:dev
```

#### Error
```
This dependency was not found:

* components/Logo in ./src/components/App/index.js
```

#### Note
The example project works if we revert [eaba11](https://github.com/KATT/create-react-app-docz-test/commit/eaba11e74460bab28c3258e238833143169c5386).

### PR DESCRIPTION
**Pull request by yaodingyd**
### Description

Add a babel plugin to use NODE_PATH for root

### Review

- [ ] Check the copy
- [ ] ...
- [ ] ...

### Pre-merge checklist

- [ ] ...
- [ ] ...

### Screenshots

| Before | After |
| ------ | ----- |
| Image  | Image |

### CODE REVIEW

**Comment by pedronauck** [comment]
Sorry dude, but I don't think that this is the best strategy for NODE_PATH. You can simply put the resolved NODE_PATH on the `resolve.modules` on webpack instead of using some new babel plugin.

**Comment by yaodingyd** [comment]
@pedronauck like the updated?

**Comment by pedronauck** [comment]
you need to set some additional code:

1. change `populateNodePath` on [this file](https://github.com/pedronauck/docz/blob/master/packages/docz-core/src/config/env.ts) to:

```js
const populateNodePath = () => {
  // We support resolving modules according to `NODE_PATH`.
  // It works similar to `NODE_PATH` in Node itself:
  // https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders
  // Note that unlike in Node, only *relative* paths from `NODE_PATH` are honored.
  // Otherwise, we risk importing Node.js core modules into an app instead of Webpack shims.
  // https://github.com/facebook/create-react-app/issues/1023#issuecomment-265344421
  // We also resolve them to make sure all tools using them work consistently.
  envDotProp.set(
    'node.path',
    envDotProp
      .get('node.path', '')
      .split(path.delimiter)
      .filter((folder: any) => folder && !path.isAbsolute(folder))
      .map((folder: any) => path.resolve(root, folder))
      .join(path.delimiter)
  )
}
```

2. then set `resolve.modules` like that:

```
config.resolve.modules
    // prioritize our own
    .add(paths.ownNodeModules)
    .add(paths.appNodeModules)
    .add('node_modules')
    .add(srcPath)
    .add(paths.root)
    .merge([
      envDotProp
        .get('node.path')
        .split(path.delimiter)
        .filter(Boolean),
    ])
``` 

And don't forget to submit your pull request on IssueHunt
https://issuehunt.io/repos/125596489/issues/396

**Comment by yaodingyd** [comment]
@pedronauck thanks! updated

**Comment by pedronauck** [comment]
thanks dude 🙏

**Comment by yaodingyd** [comment]
thank you!

**Pull request merged**
