### PR TITLE
Feat/opt out format files

### PR DESCRIPTION
**Pull request by patricksevat**
### Description

This PR addresses two issues:

1. Fixing developing on Windows (again) known under and prev fixed by #783 #812 #821 #830 CC: @ejuo 
2. Adding a configuration option to opt out of Prettier formatting.
This is useful for repo's that already do their own formatting (such as ours) and adds a feature to satisfy #813 and #865 CC: @sw-yx 

### Review

- [ ] Check the copy
- [ ] ...
- [ ] ...

### Pre-merge checklist

- [ ] ...
- [ ] ...

### Screenshots

| Before | After |
| ------ | ----- |
| Image
image  | image |

### CODE REVIEW

**Comment by rakannimer** [comment]
Hey @patricksevat 

Sorry for the late reply and thank you for taking the time to create this PR.

Could you rebase your branch with `dev` to fix the conflicts ? Or if you prefer, open a new PR with a branch starting from `dev` and with your changes only.

Would love to merge but it has conflicts.

**Comment by patricksevat** [comment]
Hi @rakannimer ,

No worries about the delay, I'm just glad that Docz is alive and kicking again thanks to you and Pedro. Really like the work you guys are doing.

Bit busy now, but I'll try to rebase in the weekend

**Comment by patricksevat** [comment]
Hi @rakannimer 

I just checked worked a bit on this, but from what I can see it appears that Prettier is no longer applied to user provided .mdx files, which is great in my opinion.

In my research I did find some things I wanted to share, and it's up to you if you want to fix it:

1. Adding a code block with three backticks does not work without providing a language:
\```
// Does not work
Hello world 
\```
\```md
// Does work
Hello world 
\```

2. `gatsby-theme-docz/src/components/Code/index.js` adds a `.trim()` on children which I'm not completely sure why. For example in Markdown code blocks you might want to space something, but this prevents it
3. `docz-utils/src/format.ts` looks like it is barely used anymore (only to template some gatsby related files) and `docz-utils/src/fs.ts` looks like it is not used at all anymore. Maybe you can verify and remove for less maintenance and dependencies

**Comment by rakannimer** [comment]
Thanks a lot @patricksevat for the report (especially the Windows issue). 

I'll add the tasks you indicated as todos and get on them ASAP.

Cheers

**Pull request closed without merging**
