### PR TITLE
Add docz-theme-default to peerDependencies of docz

### PR DESCRIPTION
**Pull request by everdimension**
Fixes https://github.com/pedronauck/docz/issues/549

### CODE REVIEW

**Comment by pedronauck** [comment]
This cause a cycled dependency, we already had this on docz. Since the newest version, because of cycled dependency, this was removed.

**Comment by everdimension** [comment]
@pedronauck I don't really mind any solution as long as there is a solution.
Right now if I follow the docs I get a broken app.

Also it's not obvious how using a custom theme would eliminate the `docz-theme-default` requirement.

**Comment by RobinCsl** [comment]
I just wanted to try docz.site this morning and I can't get it to work by following the docs.

```
Failed to compile.

./.docz/app/root.jsx
Module not found: Can't resolve 'docz-theme-default' in 'user/repo/test/.docz/app'
```

Adding `docz-theme-default` to my project dev dependencies is not helping either. I get the following in the terminal:

```
Compiled with warnings.

./node_modules/docz-theme-default/dist/index.m.js
Attempted import error: 'ClassNames' is not exported from '@emotion/core'.

./node_modules/docz-theme-default/node_modules/emotion-theming/dist/emotion-theming.browser.esm.js
Attempted import error: 'ThemeContext' is not exported from '@emotion/core'.

./node_modules/docz-theme-default/node_modules/emotion-theming/dist/emotion-theming.browser.esm.js
Attempted import error: 'ThemeContext' is not exported from '@emotion/core'.

./node_modules/docz-theme-default/node_modules/emotion-theming/dist/emotion-theming.browser.esm.js
Attempted import error: 'ThemeContext' is not exported from '@emotion/core'.

./node_modules/@emotion/cache/dist/cache.esm.js
Attempted import error: 'isBrowser' is not exported from '@emotion/utils'.

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```

and the browser console gives:

```
index.js?e094:72 Uncaught TypeError: Cannot read property 'close' of undefined
    at Object.eval (index.js?e094:72)
    at eval (index.js:230)
    at Object../node_modules/chalk/index.js (vendors.js:663)
    at __webpack_require__ (runtime~app.js:787)
    at fn (runtime~app.js:150)
    at eval (formatWebpackMessages.js?b6cb:10)
    at Object../node_modules/docz-core/node_modules/react-dev-utils/formatWebpackMessages.js (vendors.js:4978)
    at __webpack_require__ (runtime~app.js:787)
    at fn (runtime~app.js:150)
    at eval (webpackHotDevClient.js?a841:23)
(anonymous) @ index.js?e094:72
(anonymous) @ index.js:230
./node_modules/chalk/index.js @ vendors.js:663
__webpack_require__ @ runtime~app.js:787
fn @ runtime~app.js:150
(anonymous) @ formatWebpackMessages.js?b6cb:10
./node_modules/docz-core/node_modules/react-dev-utils/formatWebpackMessages.js @ vendors.js:4978
__webpack_require__ @ runtime~app.js:787
fn @ runtime~app.js:150
(anonymous) @ webpackHotDevClient.js?a841:23
./node_modules/docz-core/node_modules/react-dev-utils/webpackHotDevClient.js @ vendors.js:5002
__webpack_require__ @ runtime~app.js:787
fn @ runtime~app.js:150
0 @ app.js:43
__webpack_require__ @ runtime~app.js:787
checkDeferredModules @ runtime~app.js:46
webpackJsonpCallback @ runtime~app.js:33
(anonymous) @ app.js:1
```

I am not sure how to get this working.

**Comment by chocnut** [comment]
having the same issue too after installing docz-theme-default

**Comment by RobinCsl** [comment]
Here is a minimal repo with instructions and live demo

https://github.com/RobinCsl/minimal-docz-example/

**Pull request closed without merging**
