### PR TITLE
feat: add hook to find docgen props

### PR DESCRIPTION
**Pull request by mickaelzhang**
## Description
In some cases, we want to have access to data that we have in docgen.
Some possible use case would be to filter some general props (similarly to https://sproutsocial.com/seeds/components/alert#properties with the system props) or if you inherit props from HTMLElement and you don't want it to show.

An example of `useComponentProps`'s output would be:
```js
// For a simple Button component for example:
const output = {
  variation: { 
    defaultValue: 'secondary', 
    description: "Variation of the Button", 
    name: 'variation', 
    parent: 'path/to/component.ts', 
    required: false, 
    type: "'primary' | 'secondary'", 
  },
  isDisabled: {
    defaultValue: 'false', 
    description: "Disable state", 
    name: 'isDisabled', 
    parent: 'path/to/component.ts', 
    required: false, 
    type: "boolean", 
  },
  ...
}
```

## Related issue: 
https://github.com/doczjs/docz/issues/895

## Use case example
- In Typescript, on a component we `extends HTMLElement` => too many props (100+ maybe?)

```jsx
// path/to/HTMLElementComponent.ts

// Needed as docgen pick type from component and function only
export const HTMLElementComponent = (_: HTMLElement) => null
```
```jsx
// gatsby-theme-docz/components/Props.js

export const Props = ({ props, ...others }) => {
  const htmlElementProps = useComponentProps({ 
    componentName: 'HTMLElementComponent', 
    fileName: 'path/to/HTMLElementComponent.ts' 
  })
  const displayedProps = filterPropsLogic(props, htmlElementProps)

  return <DoczProps props={displayedProps} {...others} />
}
```

- We want to remove a multiple group of component from all components
```jsx
// path/to/SystemProps.ts

// Needed as docgen pick type from component and function only
export const MarginComponent = (_: MarginProps) => null
export const PaddingComponent = (_: PaddingProps) => null
```
```jsx
// gatsby-theme-docz/components/Props.js

export const Props = ({ props, ...others }) => {
  const marginProps = useComponentProps({ 
    componentName: 'MarginProps', 
    fileName: 'path/to/SystemProps.tss' 
  })
  const paddingProps = useComponentProps({ 
    componentName: 'PaddingProps', 
    fileName: 'path/to/SystemProps.tss' 
  })
  const displayedProps = filterPropsLogic(props, [marginProps, paddingProps])

  return <DoczProps props={displayedProps} {...others} />
}
```

_**Subject to change if it doesn't fit all use cases.**_

### CODE REVIEW

**Comment by mickaelzhang** [comment]
Hello @droganov @maryiam! 
I've been working on this and wanted get your feedback since you commented on the following issue https://github.com/doczjs/docz/issues/895

Does it fit your use case as well?

**Comment by droganov** [comment]
@mickaelzhang great, looks promising.
is there `useComponentProps` output example?

One more idea would be to patch output:

```
<DoczProps>
  {children => children.reduce(whatever)}
</DoczProps>
```

in case you can inject metadata to children

**Comment by maryiam** [comment]
Thanks !! It would be great indeed to have an example of output!

**Comment by mickaelzhang** [comment]
@droganov The output of `useComponentProps` is the same as the one you receive from the prop `props` of `<Props />` when you shadow it. So something like that:

```js
{
  propName: { defaultValue, description, name, parent, required, type },
  anotherPropName: { ... },
  ...
}
```

I'm not sure that understand your example 😅 If it's about the example that I give, you could completely change the logic if you want, the example that I give is the shadowed component so you have the complete control over that!


@aarondancer @ejuo @chunksnbits I just saw that you guys also upvoted the original issue, do you guys have an opinion on this?

**Comment by ejuo** [comment]
@mickaelzhang 
For me, the main problem is the inheritance of system properties. Docz filters them by default. But updates to the script periodically [break it](https://github.com/styleguidist/react-docgen-typescript/issues/151#issuecomment-502841346). In typescript 3.6 it fixed, but in 3.7 breaks again.
But as the additional option, perhaps it would be convenient.

**Comment by droganov** [comment]
@mickaelzhang I thought in case it outputs N rows for N props, we could inject corresponding prop to each row as static member.

Then we could iterate children knowing component name, displayName and path, and create local component that abstract that problem away.

We still could do so with the hook I think.

**Comment by mickaelzhang** [comment]
> For me, the main problem is the inheritance of system properties.

@ejuo I see, so your problem is similar to @maryiam 


@droganov Ok, I still don't understand sorry 😂 Maybe a clear example of what you want to do would help

**Comment by droganov** [comment]
@mickaelzhang 

You change `Props` component to accept function as a child:

```jsx
({ of, children }) => {
  const result = Object.entries(of).map(renderPropAndInjectMetadata);
  return typeof children === 'function' ? children(result) : result; 
}
```

Then this would keep component-only props:

```jsx
<Props of={UiComponent}>
  {renderedProps => children.filter(propRow => propRow.name === 'UiComponent' && propRow)}
</Props>
```

I mean when `Props` component knows paths it looks like a sort of overkill, to pass them as strings to the hook.

**Comment by mickaelzhang** [comment]
@droganov Ah yes, I understand now! So you have a case where you want to filter in the `mdx` file directly, per case, right?

This is a bit different than the case describe in my PR then, what I'm trying to solve is having a way to filter on all component at once with props definitions from other components.

What you are describing is possible right now by shadowing the `<Props />` component already btw

**Comment by mickaelzhang** [comment]
@droganov The use case that you describe is interesting. Maybe you could open an issue so we can discuss about this specific use case and if it should be a built-in feature?

For this PR in particular, it seems like it look good to all of you? We can move to the review part then!

**Review by rakannimer — APPROVED** [review]
This looks good to me 👍

**Comment by rakannimer** [comment]
It would also be cool if someone could add a small example to the examples directory to help others quickly know how to filter props. 👍

**Comment by maryiam** [comment]
Can you please add to the documentation the explanation on how to filter props? Thanks 🙏

**Comment by mickaelzhang** [comment]
@maryiam I will when I can find a bit of time! :)

**Comment by maryiam** [comment]
Ok thank you @mickaelzhang. Also, it would be great to mention the released version on which this feature will be available. 🙌

**Comment by mickaelzhang** [comment]
@maryiam PR opened on the documentation, https://github.com/doczjs/docz-website/pull/98

Let me know if you have any suggestion to make it clearer 👍

**Pull request merged**
