### PR TITLE
bug/ Make order ascending

### LINKED ISSUE #110: order not applying correctly
## Bug Report

**Describe the bug**

Using the `order` key in the `.mdx` file doesn't correctly reorder the menu items.

**To Reproduce**

1. Go to https://github.com/valtech-nyc/brookjs/pull/201
2. Clone the repository
3. Run `yarn && yarn docs:dev`
4. Open browser & verify menu order

**Expected behavior**

Menu should be reordered by `order` key.

**Enviroment**

* OS: OSX 10.13.5
* Node/npm version: Node 10.3.0/npm 6.1.0/yarn 1.7.0

**Additional context/Screenshots**

brookjs

### PR DESCRIPTION
**Pull request by Swapnull**
### Description

Fixes #110. 
The order is currently descending, so when the order in files is 1, 2, 3 , it displays 

- 3
- 2
- 1

This feels backwards as I would expect to start an order from 1 and count up rather than start from 100 and count down. 
 
### Review

- [ ] Check the order

### CODE REVIEW

**Comment by pedronauck** [comment]
Hmm, I think that's can be an unnecessary breaking change right now. Maybe in a possible release with a big breaking change, we can change this, but for now, I think that isn't the best option. I made the order ascending based on the `z-index` that I seem like a good option to put some things one above order.

What do you think guys? @Swapnull @marceloavf

**Comment by pedronauck** [comment]
I thinking about that and I found a non-breaking change solution. Put some attribute on `doczrc` config to define is `order` is 'ascending' or 'descending' ✌️ Something like that:

```js
// docsrz.js
export default {
  order: 'ascending'
}
```

**Comment by pedronauck** [comment]
Added manually on release [v0.5.0](https://github.com/pedronauck/docz/releases/tag/v0.5.0)

**Comment by mAAdhaTTah** [comment]
The configuration gets me what I'm looking for, but it seems like a bit of unnecessary complexity. Maybe use it as a migration path?

**Comment by mAAdhaTTah** [comment]
Right now, "descending" is default. If no value is provided, you can log a warning saying "In next release, we're going to remove this option; please change to "ascending" and update your project for forwards-compatibility." or something to that effect.

**Pull request closed without merging**
